//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fullvk.Methods.FindPosts {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResFindPost {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResFindPost() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("fullvk.Methods.FindPosts.ResFindPost", typeof(ResFindPost).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;style.css&quot; /&gt;.
        /// </summary>
        internal static string addcss {
            get {
                return ResourceManager.GetString("addcss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .post_img {
        ///    width: 50px;
        ///    height: 50px;
        ///    border-radius: 50%;
        ///    vertical-align: top
        ///}
        ///a {
        ///    color: #2a5885;
        ///    text-decoration: none;
        ///    cursor: pointer;
        ///}
        ///#date {
        ///	color:#939393;
        ///}
        ///.author{
        ///	font-weight: 500;
        ///    -webkit-font-smoothing: subpixel-antialiased;
        ///    -moz-osx-font-smoothing: auto;
        ///	display: inline-block;
        ///	margin-left: 10px;
        ///	margin-top: 10px;
        ///}
        ///.post_date {
        ///    display: -ms-flexbox;
        ///    display: flex;
        ///    white-space: pre;
        ///    position: relative;
        ///    fo [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;a href=&quot;{post_url}&quot; target=&quot;_blank&quot; class=&quot;info_div&quot; &gt;
        ///	&lt;div class=&quot;authimg&quot;&gt;
        ///		&lt;img src=&quot;{Avatar}&quot; width=&quot;50&quot; height=&quot;50&quot; class=&quot;post_img&quot; data-alt=&quot;{Author}&quot;/&gt;
        ///		&lt;div class=&quot;author&quot; &gt;{Author}&lt;br&gt;  &lt;div id=&quot;date&quot;&gt;Отправлено {DatePost}&lt;/div&gt;&lt;/div&gt;
        ///		
        ///		
        ///	&lt;/div&gt;
        ///	
        ///	&lt;div class=&quot;post&quot; &gt;
        ///		&lt;div id=&quot;post_text&quot; &gt;{TittlePost}&lt;/div&gt;
        ///		
        ///		&lt;div style=&quot;display:flex&quot; &gt;
        ///			&lt;div id=&quot;info_line&quot;&gt; Изображений: &lt;/div&gt;
        ///			&lt;div id=&quot;info_data&quot;&gt;{imgCount}&lt;/div&gt;
        ///		&lt;/div&gt;
        ///		&lt;div style=&quot;display:flex&quot; &gt;
        ///			&lt;div id=&quot; [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
    }
}
